"""Build private HTML previews only; never publish or alter app binaries."""
from pathlib import Path
from html import escape
import json

DOCS = Path(__file__).resolve().parent / 'public-repo' / 'docs'
META = json.loads((DOCS.parent / 'release.json').read_text())
V, SHA = META['version'], META['sha256']
SIZE = f"{META['sizeBytes']/1024/1024:.1f} MB"
REPO = 'https://github.com/cstrikelonghorn/LongHorn-ACS'

def icon(name):
    paths = {
        'shield':'<path d="M12 3 20 6v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
        'arrow':'<path d="M5 12h14m-6-6 6 6-6 6"/>',
        'download':'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
        'scan':'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M3 12h18"/><circle cx="12" cy="12" r="4"/>',
        'eye':'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
        'lock':'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',
        'file':'<path d="M14 3H5v18h14V8Zm0 0v5h5M8 13h8m-8 4h6"/>',
        'windows':'<path d="m3 5 8-1v7H3Zm10-1 8-1v8h-8ZM3 13h8v7l-8-1Zm10 0h8v8l-8-1Z"/>',
        'external':'<path d="M14 3h7v7m0-7L10 14m0-9H3v16h16v-7"/>',
        'search':'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
        'copy':'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v12h5"/>'}
    return f'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{paths[name]}</svg>'

def button(href,label,kind='primary',symbol='arrow'):
    return f'<a class="button {kind}" href="{href}">{label}{icon(symbol)}</a>'

def heading(number,label,title,text=''):
    return f'<div class="section-heading"><div><p class="eyebrow"><span>{number}</span>{label}</p><h2>{title}</h2></div>'+ (f'<p>{text}</p>' if text else '')+'</div>'

def question(q,a,opened=False):
    return '<details class="faq-item"'+(' open' if opened else '')+f'><summary>{q}<span class="plus" aria-hidden="true"></span></summary><div class="answer"><p>{a}</p></div></details>'

def layout(page,title,body):
    nav=''.join(f'<a href="{file}"'+(' aria-current="page"' if page==key else '')+f'>{label}</a>' for key,file,label in [('home','index.html','Overview'),('download','download.html','Download'),('faq','faq.html','FAQ'),('trust','trust.html','Trust center')])
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="LongHorn ACS private review. Counter-Strike 1.6 scanner, release information, privacy and help.">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self'; img-src 'self'; script-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'">
<title>{title} — LongHorn ACS</title><link rel="icon" href="assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>
<div class="review-strip"><div class="container"><span>{icon('lock')}PRIVATE PREVIEW <i>/</i> OWNER REVIEW</span><span class="review-note">Publication paused <span class="status-dot"></span></span></div></div>
<header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="LongHorn ACS home"><img src="assets/mark.svg" alt="" width="40" height="44"><span class="brand-type">ACS<span>BY LONGHORN</span></span></a><nav aria-label="Main navigation">{nav}</nav><a class="repo-link" href="{REPO}">{icon('lock')}<span>Private repository</span>{icon('external')}</a></div></header><main id="main">{body}</main>
<footer class="site-footer"><div class="container footer-main"><div><a class="brand footer-brand" href="index.html"><img src="assets/mark.svg" width="31" height="35" alt=""><span class="brand-type">ACS<span>BY LONGHORN</span></span></a><p>Game integrity. Clear evidence.<br>Built for the Counter-Strike community.</p></div><div><span class="footer-label">PRODUCT</span><a href="index.html">Overview</a><a href="download.html">Download</a><a href="faq.html">Help &amp; FAQ</a></div><div><span class="footer-label">TRANSPARENCY</span><a href="trust.html">Trust center</a><a href="trust.html#privacy">Privacy &amp; data</a><a href="trust.html#ownership">Copyright &amp; notices</a></div><div class="footer-status"><span class="footer-label">RELEASE CHANNEL</span><span class="badge">{icon('lock')} PRIVATE BETA</span><p>v{V}<br>Windows x64</p></div></div><div class="container footer-bottom"><span>© 2026 LongHorn. Original material reserved.</span><span>Independent project. Not affiliated with Valve.</span><a href="{REPO}/blob/main/LICENSE.md">Permissions &amp; third-party rights {icon('external')}</a></div></footer></body></html>'''

radar=f'''<div class="scanner-preview"><div class="console-bar"><span><span class="status-dot"></span>ACS / INTEGRITY SCANNER</span><span class="mono muted">PREVIEW_01</span></div><div class="scan-stage"><div class="stage-corner tl"></div><div class="stage-corner tr"></div><div class="stage-corner bl"></div><div class="stage-corner br"></div><span class="coordinate top-left">GOLDSRC / 1.6</span><span class="coordinate bottom-right">ON-DEMAND SCAN</span><div class="radar" aria-hidden="true"><div class="radar-ticks"></div><div class="radar-sweep"></div><div class="radar-inner"></div><span class="radar-axis horizontal"></span><span class="radar-axis vertical"></span></div><div class="radar-label">{icon('shield')}<strong>STANDBY</strong><span>AWAITING YOUR COMMAND</span></div></div><div class="console-cells"><div><span>01 / SCAN</span><strong>Game integrity</strong></div><div><span>02 / REVIEW</span><strong>Your evidence</strong></div><div><span>03 / DECIDE</span><strong>Your approval</strong></div></div><div class="console-foot">{icon('eye')}Illustrative interface · no live scan or player data</div></div>'''

home=f'''<section class="container hero"><div class="hero-copy"><p class="eyebrow"><span class="eyebrow-line"></span>COUNTER-STRIKE 1.6 / GOLDSRC</p><h1>FAIR PLAY.<br><span>CLEAR EVIDENCE.</span></h1><p class="hero-lead">A closer look at the game you play.</p><p class="hero-description">Inspect game integrity, review suspicious signals, and see exactly what your scan contains before you share it.</p><div class="actions">{button('download.html','Explore the scanner',symbol='download')}{button('trust.html','How it works','secondary')}</div><div class="hero-meta"><span>{icon('windows')}Windows x64</span><span>Portable app</span><span>Private beta</span></div></div>{radar}</section>
<div class="container"><div class="compatibility-strip"><span class="eyebrow">BUILT AROUND<br>YOUR GAME</span><div><strong>GOLDSRC</strong><small>ENGINE</small></div><div><strong>COUNTER-STRIKE</strong><small>VERSION 1.6</small></div><div><strong>WINDOWS</strong><small>64-BIT DESKTOP</small></div><a href="faq.html#compatibility">Client compatibility {icon('arrow')}</a></div></div>
<section class="container section">{heading('01','THE SCANNER','Every signal. In context.','Designed to help players and server operators make informed decisions from reviewable evidence.')}<div class="feature-grid">'''
for n,symbol,title,desc,link,label in [
('01','scan','Inspect game integrity.','Review loaded modules, game files, configuration scripts and memory evidence during an on-demand scan.','faq.html#scanning','What the scanner checks'),
('02','eye','See the full picture.','Read the complete report before upload. Findings and warnings need context; the operator makes enforcement decisions.','faq.html#reports','Understanding reports'),
('03','lock','Stay in control.','Start the scan yourself. Check the destination. Choose whether to send your report to your server operator.','trust.html#privacy','Privacy &amp; data access')]:
    home+=f'<article class="feature-card"><span class="feature-index">{n}</span><div class="feature-icon">{icon(symbol)}</div><h3>{title}</h3><p>{desc}</p><a href="{link}">{label}{icon("arrow")}</a></article>'
home+=f'''</div></section><section class="workflow-section"><div class="container workflow-grid"><div><p class="eyebrow"><span>02</span>FROM GAME TO EVIDENCE</p><h2>Three steps.<br>A clearer decision.</h2><p>No hidden report upload. Review the data and the recipient before you approve sharing.</p>{button('download.html#setup','Read the setup guide','text-button')}</div><ol class="workflow"><li><span>01</span><div><h3>Launch &amp; configure</h3><p>Start Counter-Strike and use the HTTPS settings provided by an operator you trust.</p></div></li><li><span>02</span><div><h3>Scan &amp; inspect</h3><p>Read the disclosure, start the scan, and review the complete JSON report.</p></div></li><li><span>03</span><div><h3>Choose what happens next</h3><p>Approve the upload or decline it. The earlier rule download still contacts your configured server.</p></div></li></ol></div></section>
<section class="container section"><div class="trust-banner"><div class="trust-symbol">{icon('shield')}</div><div><p class="eyebrow">TRANSPARENCY BY DESIGN</p><h2>Trust needs evidence.</h2><p>Release hashes, clear data-access information, and honest review status. No safety badges without supporting evidence.</p></div>{button('trust.html','Visit the trust center','secondary')}</div></section>
<section class="container section home-faq">{heading('03','BEFORE YOU START','A few good questions.')}<div class="faq-list">{question('Is the app ready for public release?','Not yet. This is a private beta under owner review. The download is held, and signing, independent review, artwork permissions and backend configuration remain outstanding.')}{question('Is my report uploaded automatically?','The official desktop interface shows the full report and asks for approval before upload. Declining or closing the preview does not send the report. Rule downloads contact the configured operator before that decision.')}{question('Does a clean scan prove a player is cheat-free?','No. A scan is a limited observation. Unknown cheats, evasion and unavailable inspection surfaces can affect results. Findings require review.')}</div><a class="inline-link" href="faq.html">Explore the full FAQ {icon('arrow')}</a></section>'''

download=f'''<section class="container page-heading"><p class="eyebrow"><span>DOWNLOAD CENTER</span>WINDOWS DESKTOP</p><h1>YOUR NEXT<br><span>INTEGRITY CHECK.</span></h1><p>The ACS desktop scanner. Portable, transparent, and built around your Counter-Strike session.</p></section>
<section class="container download-layout"><article class="release-card"><div class="release-top"><span class="badge">{icon('lock')}PRIVATE BETA</span><span class="mono muted">WIN / X64</span></div><div class="product-title"><div class="product-icon">{icon('shield')}</div><div><span class="eyebrow">LONGHORN</span><h2>ACS Scanner</h2><p>Counter-Strike 1.6 · GoldSrc</p></div></div><dl class="release-specs"><div><dt>VERSION</dt><dd>{V}</dd></div><div><dt>PACKAGE SIZE</dt><dd>{SIZE}</dd></div><div><dt>DISTRIBUTION</dt><dd>Portable ZIP</dd></div><div><dt>RUNTIME</dt><dd>Included</dd></div></dl><button class="button primary download-held" disabled>{icon('lock')}Release held for owner review</button><p class="download-note">Public downloads are paused. The existing package is retained as a draft in the private repository.</p><a class="inline-link" href="{REPO}/releases">Open private release drafts {icon('external')}</a><div class="release-card-bottom">{icon('file')}Extract the complete package. Keep its libraries and Assets folder together.</div></article><aside class="release-sidebar"><div class="panel"><p class="eyebrow">BEFORE YOU INSTALL</p><h3>Know the current status.</h3><ul class="status-list"><li><span>Publisher signature</span><strong>Unsigned</strong></li><li><span>Independent audit</span><strong>Pending</strong></li><li><span>Antivirus analysis</span><strong>Not verified</strong></li><li><span>Report destination</span><strong>Not configured</strong></li></ul><a class="inline-link" href="trust.html">Evidence &amp; limitations {icon('arrow')}</a></div><div class="sidebar-note">{icon('windows')}<div><h3>Windows x64</h3><p>A compatible running game and operator-provided HTTPS API settings are required. This is not a standalone offline scanner.</p></div></div></aside></section>
<section class="container section" id="verify">{heading('01','FILE VERIFICATION','Identify the exact package.','A checksum confirms that a file matches this build. It does not certify safety.')}<div class="checksum-panel"><div class="checksum-heading"><span class="badge">SHA-256</span><span class="mono">{escape(META['asset'])}</span><button class="copy-button" data-copy="package-hash" aria-label="Copy package SHA-256">{icon('copy')}<span>Copy hash</span></button></div><code id="package-hash" class="hash-value">{SHA}</code><p class="copy-status" role="status" aria-live="polite"></p></div><div class="resource-links"><a href="{REPO}/blob/main/FILE-MANIFEST.json">{icon('file')}File manifest {icon('external')}</a><a href="{REPO}/blob/main/DEPENDENCIES.json">{icon('file')}Dependencies {icon('external')}</a><a href="{REPO}/blob/main/VERIFY.md">{icon('shield')}Verification guide {icon('external')}</a></div></section>
<section class="container section" id="setup">{heading('02','GETTING STARTED','Ready when you are.')}<div class="setup-grid"><article><span class="step-number">01</span><h3>Extract the package</h3><p>When a release is approved, compare its hash and extract the full ZIP into a folder you control.</p></article><article><span class="step-number">02</span><h3>Connect your operator</h3><p>Obtain a trusted HTTPS report endpoint and any required credential. Keep credentials out of public reports and issues.</p></article><article><span class="step-number">03</span><h3>Launch &amp; review</h3><p>Start the game, read the scan disclosure, and inspect the report. Approve the upload only when you accept its contents and destination.</p></article></div></section>
<section class="container section">{heading('03','RELEASE NOTES','What changed.')}<div class="changelog"><div><span class="change-tag">PRIVACY</span><p>Added a disclosure before scanning and full report review before upload.</p></div><div><span class="change-tag">CONTROL</span><p>Missing approval, declining, or closing the preview prevents report upload.</p></div><div><span class="change-tag">CLARITY</span><p>Added a clear message when no report destination is configured.</p></div></div><a class="inline-link" href="{REPO}/blob/main/RELEASE_NOTES.md">Complete release notes {icon('external')}</a></section>'''

groups=[
('basics','Getting started',[
('What is LongHorn ACS?','ACS is an on-demand Windows evidence scanner for Counter-Strike 1.6 and GoldSrc. It inspects game integrity and suspicious signals, then lets you review a report before sending it to a configured operator.'),
('Can I download and use it now?','Public distribution is paused while the owner reviews this beta. The private repository retains a draft package. The app also needs a real report backend; the GitHub repository and this information site do not receive scans.'),
('Does the package install a service or kernel driver?','No. This package is a portable desktop app with its runtime included. It does not bundle the optional server plugin or kernel-driver scaffold. Close the app and remove its extracted folder to remove the package; this does not delete reports already uploaded to an operator.')]),
('compatibility','Game & client compatibility',[
('Which games and clients does ACS target?','Counter-Strike 1.6 on GoldSrc. Profiles include Steam and non-Steam distributions, NextClient, GoldClient, GSClient and RevEmu, plus recognition of server-platform components. These are compatibility targets, not a guarantee for every version or modification.'),
('What about ReHLDS, ReAPI and Reunion?','These are server-side components, not interchangeable desktop clients. Continuous server gameplay analysis requires a separately deployed and configured server plugin. That plugin is not included in this desktop download.'),
('Does it work on every version of Windows?','This package targets Windows x64. Validation was performed on the maintainer’s Windows machine; a complete Windows-version and client-build test matrix has not been completed. There is no native macOS or Linux release in this package.')]),
('scanning','Scanning & detection',[
('What does the scanner inspect?','The running game, modules, executable memory, drivers, other processes, game files and configs, aliases, suspicious handles/windows/threads, and execution, download and recent deletion traces. It briefly samples cursor and game-button state during scanning. Read the full data-access notice before running it.'),
('Does it detect every wallhack, ESP, aimbot or script?','No universal detection guarantee is made. Findings depend on available evidence, current rules, scan coverage and the specific cheat. Unknown tools, evasion and restricted access can affect detection. No measured superiority to VAC, WarGods or ECD is claimed.'),
('Is this continuous protection during gameplay?','The desktop app scans on demand. It is not a continuously running prevention system. Gameplay telemetry from a server plugin is a separate deployment.'),
('How are detection rules updated?','The scanner requests rules from the configured report service. The operator is responsible for maintaining and reviewing that rule set. There is no claim that a universal database contains every newly published cheat.')]),
('reports','Reports & privacy',[
('What personal data can a report contain?','Player/Steam identifiers, machine name, device fingerprint and volume serial, paths and hashes, process and module details, game/server information, memory strings, findings and timings. The receiving operator also sees your IP address. Inspect the exact JSON preview for your scan.'),
('Can I refuse to upload the report?','Yes. The official desktop interface requires approval after showing the full report. Declining or closing the preview prevents that report upload. The earlier rule request still contacts the configured server and exposes your IP address to it.'),
('Who can see my report, and when is it deleted?','Your operator controls report access, storage and retention. There is no automatic expiry guarantee. Ask the operator about private access and deletion before scanning; the client cannot remove records already stored on a server.'),
('Does a warning mean someone is cheating?','No. A warning is a signal for review. Compatibility changes, legitimate tools or incomplete evidence may need interpretation. A scan with no findings also does not prove a player is cheat-free. Enforcement decisions belong to the operator.')]),
('ownership','Safety, source & ownership',[
('Is this app independently certified safe?','No. The beta is unsigned and has not completed an independent audit or verified antivirus analysis for this exact build. Published hashes identify files; they are not a safety certificate. Keep normal Windows protections enabled.'),
('Will scanner source code be published here?','This is a distribution and documentation repository. Scanner/server source, detection databases, secrets and player reports remain outside it. Website HTML, CSS and JavaScript are presentation code and will be inspectable if the site is later published. Compiled applications can still be reverse engineered.'),
('Can someone copy the application or website?','Copyright and permission notices state the maintainer’s intended terms; they are not technical copy protection. Third-party rights and licenses remain in effect. The draft app’s legacy artwork still needs permission review or replacement before publication.'),
('How do I report a problem?','Use the private repository’s issue tracker with a version number and a sanitized reproduction. Never attach credentials, player identifiers or real report data to an ordinary issue. For a security vulnerability, use GitHub private vulnerability reporting when available.')])]
faq_sections=''.join(f'<section class="faq-group" id="{key}" data-faq-group><div class="faq-group-heading"><span class="eyebrow">{i+1:02}</span><h2>{escape(name)}</h2></div>'+''.join(question(q,escape(a),i==0 and j==0) for j,(q,a) in enumerate(items))+'</section>' for i,(key,name,items) in enumerate(groups))
faq=f'''<section class="container page-heading compact"><p class="eyebrow"><span>HELP CENTER</span>UNDERSTAND YOUR SCAN</p><h1>GOOD QUESTIONS.<br><span>CLEAR ANSWERS.</span></h1><p>From your first scan to report privacy. Everything you should know before getting started.</p><div class="faq-search" hidden data-search-box>{icon('search')}<label class="sr-only" for="faq-search">Search frequently asked questions</label><input id="faq-search" type="search" placeholder="Search setup, privacy, compatibility…" autocomplete="off"><span class="mono">FAQ</span></div><p id="search-status" class="search-status" role="status" aria-live="polite"></p></section><div class="container faq-layout"><aside class="faq-nav"><span class="eyebrow">ON THIS PAGE</span><nav aria-label="FAQ categories">{''.join(f'<a href="#{key}">{escape(name)}{icon("arrow")}</a>' for key,name,_ in groups)}</nav><div class="faq-help">{icon('file')}<h3>Need more detail?</h3><p>Read the complete data-access and validation documents.</p><a href="trust.html">Visit trust center {icon('arrow')}</a></div></aside><div class="faq-content">{faq_sections}<div class="empty-search" hidden><h2>No matching questions.</h2><p>Try a shorter term such as “report”, “Windows”, or “privacy”.</p></div></div></div><section class="container section"><div class="help-banner"><div><p class="eyebrow">STILL NEED HELP?</p><h2>Keep the conversation private.</h2><p>Share a sanitized example with the maintainer. Leave credentials and player data out of issues.</p></div>{button(REPO+'/issues','Open private support','secondary','external')}</div></section>'''

trust=f'''<section class="container page-heading compact"><p class="eyebrow"><span>TRUST CENTER</span>TRANSPARENCY &amp; CONTROL</p><h1>TRUST IS EARNED.<br><span>HERE’S THE EVIDENCE.</span></h1><p>What the scanner accesses. What we have checked. What still needs work.</p></section><section class="container"><div class="trust-status-grid"><article><span>01 / DISTRIBUTION</span><strong>Private beta</strong><p>Owner review in progress.</p></article><article><span>02 / SIGNATURE</span><strong>Unsigned</strong><p>No publisher signature yet.</p></article><article><span>03 / INDEPENDENT AUDIT</span><strong>Not completed</strong><p>No independent safety claim.</p></article><article><span>04 / REPORT SHARING</span><strong>Your approval</strong><p>Review before upload.</p></article></div></section>
<section class="container section" id="privacy">{heading('01','PRIVACY & DATA ACCESS','Know what you’re sharing.')}<div class="privacy-grid"><article class="panel"><div class="feature-icon">{icon('scan')}</div><h3>During the scan</h3><p>ACS inspects the game and related system evidence, including modules, drivers, processes, files, memory and activity traces. It briefly samples cursor and game-button state.</p><p>The rule download contacts your configured operator before you decide whether to send the final report.</p></article><article class="panel"><div class="feature-icon">{icon('eye')}</div><h3>Before the upload</h3><p>The full JSON preview can include player and device identifiers, machine name, paths, hashes, memory strings, game/server details and findings.</p><p>Read it and check the destination. Decline or close the preview to prevent the report upload.</p></article></div><div class="notice">{icon('lock')}<div><strong>Retention belongs to your operator.</strong><p>Report access, backups and deletion depend on the receiving service. No automatic expiry or remote deletion guarantee is provided by the client.</p><a href="{REPO}/blob/main/PRIVACY.md">Complete privacy notice {icon('external')}</a></div></div></section>
<section class="container section" id="validation">{heading('02','DEVELOPER VALIDATION','Checks you can review.','Synthetic checks validate selected behavior. They are not an independent audit or a real-world detection benchmark.')}<div class="table-wrap"><table><caption class="sr-only">Developer test results for the draft release</caption><thead><tr><th scope="col">CHECK</th><th scope="col">RESULT</th><th scope="col">SCOPE</th></tr></thead><tbody><tr><th scope="row">Desktop regression</th><td><span class="result-pass">19 passed</span></td><td>Detection boundaries, consent gate, cancellation and UI render</td></tr><tr><th scope="row">Backend regression</th><td><span class="result-pass">7 suites passed</span></td><td>103 assertions across ingest, access, risk and reputation</td></tr><tr><th scope="row">Signature feeds</th><td><span class="result-pass">5 passed</span></td><td>Payload integrity and input validation</td></tr><tr><th scope="row">Release build</th><td><span class="result-review">Warnings remain</span></td><td>0 errors · 131 compiler warnings</td></tr></tbody></table></div><div class="resource-links"><a href="{REPO}/blob/main/VALIDATION.md">{icon('file')}Validation &amp; limits {icon('external')}</a><a href="download.html#verify">{icon('shield')}Package verification {icon('arrow')}</a></div></section>
<section class="container section" id="ownership">{heading('03','SOURCE & OWNERSHIP','Private implementation.<br>Clear permissions.')}<div class="privacy-grid"><article class="panel"><h3>What stays private</h3><p>Scanner and server source, detection databases, credentials and player reports are excluded from this distribution repository.</p><p>Compiled software can still be reverse engineered. A public website’s HTML, CSS and JavaScript are visible to its visitors.</p></article><article class="panel"><h3>Copyright &amp; third parties</h3><p>LongHorn reserves rights in its original material. Third-party licenses, artwork rights and trademarks remain with their owners.</p><p>The draft app’s existing artwork needs permission review or replacement before public release. This redesigned site uses original geometric visuals.</p><a href="{REPO}/blob/main/ASSET-NOTICES.md">Asset review &amp; notices {icon('external')}</a></article></div></section><section class="container section"><div class="help-banner"><div><p class="eyebrow">RESPONSIBLE REPORTING</p><h2>Found a security concern?</h2><p>Use a private vulnerability report with synthetic evidence. Never include real player data, credentials or private report links.</p></div>{button(REPO+'/security/advisories/new','Report privately','secondary','shield')}</div></section>'''

for key,file,title,body in [('home','index.html','Game integrity. Clear evidence.',home),('download','download.html','Download center',download),('faq','faq.html','Help & FAQ',faq),('trust','trust.html','Trust center',trust)]:
    (DOCS/file).write_text(layout(key,title,body),encoding='utf-8')
(DOCS/'assets/mark.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 48"><path d="M22 2 41 9v17L22 46 3 26V9Z" fill="#151a20" stroke="#eeb34f" stroke-width="1.6"/><path d="m12 29 10-17 10 17h-5l-5-9-5 9Zm7-2h6v5h-6Z" fill="#eeb34f"/><path d="m7 12 5-2m20 0 5 2M22 40v-4" stroke="#5ad6ff" stroke-width="1.5"/></svg>',encoding='utf-8')
print('Prepared four private review pages. No publishing or binary changes performed.')
